version: "3.2"
services:

  php:
    environment:
      TZ: "Europe/Prague"
    build: ./../_docker/php/
    networks:
      - backend
#      - frontend
    volumes:
      - ./TigerCore/:/var/www/

networks:
#  frontend:
  backend:


#volumes:
#  form:
